### ISSUE TITLE
Remove log messages

### ISSUE THREAD

**Issue by marioguerriero** [ISMAELMARTINEZ/gridfs-storage-engine#4]
When instantiating a new gridfs-storage-engine object by doing:

```javascript
var gridfs = require("gridfs-storage-engine")({
  database: db
});
```

I get a log message saying: "mongoDB connected"

Moreover it logs file's information any time I save one.

Could you please drop connection status log messages?
 
Also, could you please edit the file saving log so that it logs only the file's id?

By the way, thanks for this amazing module.

**Comment by marioguerriero** [comment]
A made a fix for this easy to fix issue. I hope you will merge it.

#https://github.com/ISMAELMARTINEZ/gridfs-storage-engine/compare/master...marioguerriero:master

**Comment by ISMAELMARTINEZ** [comment]
Hi @marioguerriero ,

1st of all apologies for taking that long to reply. I have been on holidays, then busy and forgot to reply to it. 

I got a concern in question of logs. I tend to log all and then use another tool like https://github.com/winstonjs/winston to tune the level of login. This helps on development and production.

I will probably prefer to be able to switch it on/off than to remove them.

What do you think? 

Regards,

**Comment by marioguerriero** [comment]
Hi,

I was not aware of Winston. Maybe using it could be a nice solution but I think one good thing would be to make logs more releated to this library.

What I mean is that before any log message (eg "mongoDB connected") we could add a string to let the users be aware that it comes from gridfs-storage-engine (eg "gridfs-storage-engine: mongoDB connected") and then use Winston or whatever the user wants to tune the level of logging.

I know this is a stupid issue but the  first time I used this library I could not catch where those logging messages came from and it was a little annoying.

**Comment by ISMAELMARTINEZ** [comment]
No issue is stupid and is a totally valid reason. 

Feel free to change it and do a merge request. I will add it as soon as I can (probably will need to wait till Monday)

Thanks a lot for contributing to the open source community!

**Comment by marioguerriero** [comment]
Sorry but I won't be able to make any push for some time. Add it on Monday if you can or I will do it as soon as possible.

**Comment by marioguerriero** [comment]
Ok, despite what I said I was able to push this little fix. I made a pull request: https://github.com/ISMAELMARTINEZ/gridfs-storage-engine/pull/5

**Comment by ISMAELMARTINEZ** [comment]
Added and publish that as part of #5
